export const positionDict: Record<string, string> = {
    Attacker: "FW",
    Midfielder: "MF",
    Defender: "DF",
    Goalkeeper: "GK",
};

export const nationalityDict: Record<string, string> = {
    England: "GB-ENG",
    USA: "US",
    Türkiye: "TR",
    Scotland: "GB-SCT",
    Czechia: "CZ",
    Russia: "RU",
    Wales: "GB-WLS",
    Venezuela: "VE",
    Iran: "IR",
    "Korea Republic": "KR",
    "Congo DR": "CD",
    "Northern Ireland": "GB-NIR",
    "Republic of Ireland": "IE",
    "North Macedonia": "MK",
};

export const letterDict: Record<string, string> = {
    Á: "A",
    Ă: "A",
    Ắ: "A",
    Ặ: "A",
    Ằ: "A",
    Ẳ: "A",
    Ẵ: "A",
    Ǎ: "A",
    Â: "A",
    Ấ: "A",
    Ậ: "A",
    Ầ: "A",
    Ẩ: "A",
    Ẫ: "A",
    Ä: "A",
    Ǟ: "A",
    Ȧ: "A",
    Ǡ: "A",
    Ạ: "A",
    Ȁ: "A",
    À: "A",
    Ả: "A",
    Ȃ: "A",
    Ā: "A",
    Ą: "A",
    Å: "A",
    Ǻ: "A",
    Ḁ: "A",
    Ⱥ: "A",
    Ã: "A",
    Ꜳ: "AA",
    Æ: "AE",
    Ǽ: "AE",
    Ǣ: "AE",
    Ꜵ: "AO",
    Ꜷ: "AU",
    Ꜹ: "AV",
    Ꜻ: "AV",
    Ꜽ: "AY",
    Ḃ: "B",
    Ḅ: "B",
    Ɓ: "B",
    Ḇ: "B",
    Ƀ: "B",
    Ƃ: "B",
    Ć: "C",
    Č: "C",
    Ç: "C",
    Ḉ: "C",
    Ĉ: "C",
    Ċ: "C",
    Ƈ: "C",
    Ȼ: "C",
    Ď: "D",
    Ḑ: "D",
    Ḓ: "D",
    Ḋ: "D",
    Ḍ: "D",
    Ɗ: "D",
    Ḏ: "D",
    ǲ: "D",
    ǅ: "D",
    Đ: "D",
    Ƌ: "D",
    Ǳ: "DZ",
    Ǆ: "DZ",
    É: "E",
    Ĕ: "E",
    Ě: "E",
    Ȩ: "E",
    Ḝ: "E",
    Ê: "E",
    Ế: "E",
    Ệ: "E",
    Ề: "E",
    Ể: "E",
    Ễ: "E",
    Ḙ: "E",
    Ë: "E",
    Ė: "E",
    Ẹ: "E",
    Ȅ: "E",
    È: "E",
    Ẻ: "E",
    Ȇ: "E",
    Ē: "E",
    Ḗ: "E",
    Ḕ: "E",
    Ę: "E",
    Ɇ: "E",
    Ẽ: "E",
    Ḛ: "E",
    Ꝫ: "ET",
    Ḟ: "F",
    Ƒ: "F",
    Ǵ: "G",
    Ğ: "G",
    Ǧ: "G",
    Ģ: "G",
    Ĝ: "G",
    Ġ: "G",
    Ɠ: "G",
    Ḡ: "G",
    Ǥ: "G",
    Ḫ: "H",
    Ȟ: "H",
    Ḩ: "H",
    Ĥ: "H",
    Ⱨ: "H",
    Ḧ: "H",
    Ḣ: "H",
    Ḥ: "H",
    Ħ: "H",
    Í: "I",
    Ĭ: "I",
    Ǐ: "I",
    Î: "I",
    Ï: "I",
    Ḯ: "I",
    İ: "I",
    Ị: "I",
    Ȉ: "I",
    Ì: "I",
    Ỉ: "I",
    Ȋ: "I",
    Ī: "I",
    Į: "I",
    Ɨ: "I",
    Ĩ: "I",
    Ḭ: "I",
    Ꝺ: "D",
    Ꝼ: "F",
    Ᵹ: "G",
    Ꞃ: "R",
    Ꞅ: "S",
    Ꞇ: "T",
    Ꝭ: "IS",
    Ĵ: "J",
    Ɉ: "J",
    Ḱ: "K",
    Ǩ: "K",
    Ķ: "K",
    Ⱪ: "K",
    Ꝃ: "K",
    Ḳ: "K",
    Ƙ: "K",
    Ḵ: "K",
    Ꝁ: "K",
    Ꝅ: "K",
    Ĺ: "L",
    Ƚ: "L",
    Ľ: "L",
    Ļ: "L",
    Ḽ: "L",
    Ḷ: "L",
    Ḹ: "L",
    Ⱡ: "L",
    Ꝉ: "L",
    Ḻ: "L",
    Ŀ: "L",
    Ɫ: "L",
    ǈ: "L",
    Ł: "L",
    Ǉ: "LJ",
    Ḿ: "M",
    Ṁ: "M",
    Ṃ: "M",
    Ɱ: "M",
    Ń: "N",
    Ň: "N",
    Ņ: "N",
    Ṋ: "N",
    Ṅ: "N",
    Ṇ: "N",
    Ǹ: "N",
    Ɲ: "N",
    Ṉ: "N",
    Ƞ: "N",
    ǋ: "N",
    Ñ: "N",
    Ǌ: "NJ",
    Ó: "O",
    Ŏ: "O",
    Ǒ: "O",
    Ô: "O",
    Ố: "O",
    Ộ: "O",
    Ồ: "O",
    Ổ: "O",
    Ỗ: "O",
    Ö: "O",
    Ȫ: "O",
    Ȯ: "O",
    Ȱ: "O",
    Ọ: "O",
    Ő: "O",
    Ȍ: "O",
    Ò: "O",
    Ỏ: "O",
    Ơ: "O",
    Ớ: "O",
    Ợ: "O",
    Ờ: "O",
    Ở: "O",
    Ỡ: "O",
    Ȏ: "O",
    Ꝋ: "O",
    Ꝍ: "O",
    Ō: "O",
    Ṓ: "O",
    Ṑ: "O",
    Ɵ: "O",
    Ǫ: "O",
    Ǭ: "O",
    Ø: "O",
    Ǿ: "O",
    Õ: "O",
    Ṍ: "O",
    Ṏ: "O",
    Ȭ: "O",
    Ƣ: "OI",
    Ꝏ: "OO",
    Ɛ: "E",
    Ɔ: "O",
    Ȣ: "OU",
    Ṕ: "P",
    Ṗ: "P",
    Ꝓ: "P",
    Ƥ: "P",
    Ꝕ: "P",
    Ᵽ: "P",
    Ꝑ: "P",
    Ꝙ: "Q",
    Ꝗ: "Q",
    Ŕ: "R",
    Ř: "R",
    Ŗ: "R",
    Ṙ: "R",
    Ṛ: "R",
    Ṝ: "R",
    Ȑ: "R",
    Ȓ: "R",
    Ṟ: "R",
    Ɍ: "R",
    Ɽ: "R",
    Ꜿ: "C",
    Ǝ: "E",
    Ś: "S",
    Ṥ: "S",
    Š: "S",
    Ṧ: "S",
    Ş: "S",
    Ŝ: "S",
    Ș: "S",
    Ṡ: "S",
    Ṣ: "S",
    Ṩ: "S",
    Ť: "T",
    Ţ: "T",
    Ṱ: "T",
    Ț: "T",
    Ⱦ: "T",
    Ṫ: "T",
    Ṭ: "T",
    Ƭ: "T",
    Ṯ: "T",
    Ʈ: "T",
    Ŧ: "T",
    Ɐ: "A",
    Ꞁ: "L",
    Ɯ: "M",
    Ʌ: "V",
    Ꜩ: "TZ",
    Ú: "U",
    Ŭ: "U",
    Ǔ: "U",
    Û: "U",
    Ṷ: "U",
    Ü: "U",
    Ǘ: "U",
    Ǚ: "U",
    Ǜ: "U",
    Ǖ: "U",
    Ṳ: "U",
    Ụ: "U",
    Ű: "U",
    Ȕ: "U",
    Ù: "U",
    Ủ: "U",
    Ư: "U",
    Ứ: "U",
    Ự: "U",
    Ừ: "U",
    Ử: "U",
    Ữ: "U",
    Ȗ: "U",
    Ū: "U",
    Ṻ: "U",
    Ų: "U",
    Ů: "U",
    Ũ: "U",
    Ṹ: "U",
    Ṵ: "U",
    Ꝟ: "V",
    Ṿ: "V",
    Ʋ: "V",
    Ṽ: "V",
    Ꝡ: "VY",
    Ẃ: "W",
    Ŵ: "W",
    Ẅ: "W",
    Ẇ: "W",
    Ẉ: "W",
    Ẁ: "W",
    Ⱳ: "W",
    Ẍ: "X",
    Ẋ: "X",
    Ý: "Y",
    Ŷ: "Y",
    Ÿ: "Y",
    Ẏ: "Y",
    Ỵ: "Y",
    Ỳ: "Y",
    Ƴ: "Y",
    Ỷ: "Y",
    Ỿ: "Y",
    Ȳ: "Y",
    Ɏ: "Y",
    Ỹ: "Y",
    Ź: "Z",
    Ž: "Z",
    Ẑ: "Z",
    Ⱬ: "Z",
    Ż: "Z",
    Ẓ: "Z",
    Ȥ: "Z",
    Ẕ: "Z",
    Ƶ: "Z",
    Ĳ: "IJ",
    Œ: "OE",
    ᴀ: "A",
    ᴁ: "AE",
    ʙ: "B",
    ᴃ: "B",
    ᴄ: "C",
    ᴅ: "D",
    ᴇ: "E",
    ꜰ: "F",
    ɢ: "G",
    ʛ: "G",
    ʜ: "H",
    ɪ: "I",
    ʁ: "R",
    ᴊ: "J",
    ᴋ: "K",
    ʟ: "L",
    ᴌ: "L",
    ᴍ: "M",
    ɴ: "N",
    ᴏ: "O",
    ɶ: "OE",
    ᴐ: "O",
    ᴕ: "OU",
    ᴘ: "P",
    ʀ: "R",
    ᴎ: "N",
    ᴙ: "R",
    ꜱ: "S",
    ᴛ: "T",
    ⱻ: "E",
    ᴚ: "R",
    ᴜ: "U",
    ᴠ: "V",
    ᴡ: "W",
    ʏ: "Y",
    ᴢ: "Z",
    á: "a",
    ă: "a",
    ắ: "a",
    ặ: "a",
    ằ: "a",
    ẳ: "a",
    ẵ: "a",
    ǎ: "a",
    â: "a",
    ấ: "a",
    ậ: "a",
    ầ: "a",
    ẩ: "a",
    ẫ: "a",
    ä: "a",
    ǟ: "a",
    ȧ: "a",
    ǡ: "a",
    ạ: "a",
    ȁ: "a",
    à: "a",
    ả: "a",
    ȃ: "a",
    ā: "a",
    ą: "a",
    ᶏ: "a",
    ẚ: "a",
    å: "a",
    ǻ: "a",
    ḁ: "a",
    ⱥ: "a",
    ã: "a",
    ꜳ: "aa",
    æ: "ae",
    ǽ: "ae",
    ǣ: "ae",
    ꜵ: "ao",
    ꜷ: "au",
    ꜹ: "av",
    ꜻ: "av",
    ꜽ: "ay",
    ḃ: "b",
    ḅ: "b",
    ɓ: "b",
    ḇ: "b",
    ᵬ: "b",
    ᶀ: "b",
    ƀ: "b",
    ƃ: "b",
    ɵ: "o",
    ć: "c",
    č: "c",
    ç: "c",
    ḉ: "c",
    ĉ: "c",
    ɕ: "c",
    ċ: "c",
    ƈ: "c",
    ȼ: "c",
    ď: "d",
    ḑ: "d",
    ḓ: "d",
    ȡ: "d",
    ḋ: "d",
    ḍ: "d",
    ɗ: "d",
    ᶑ: "d",
    ḏ: "d",
    ᵭ: "d",
    ᶁ: "d",
    đ: "d",
    ɖ: "d",
    ƌ: "d",
    ı: "i",
    ȷ: "j",
    ɟ: "j",
    ʄ: "j",
    ǳ: "dz",
    ǆ: "dz",
    é: "e",
    ĕ: "e",
    ě: "e",
    ȩ: "e",
    ḝ: "e",
    ê: "e",
    ế: "e",
    ệ: "e",
    ề: "e",
    ể: "e",
    ễ: "e",
    ḙ: "e",
    ë: "e",
    ė: "e",
    ẹ: "e",
    ȅ: "e",
    è: "e",
    ẻ: "e",
    ȇ: "e",
    ē: "e",
    ḗ: "e",
    ḕ: "e",
    ⱸ: "e",
    ę: "e",
    ᶒ: "e",
    ɇ: "e",
    ẽ: "e",
    ḛ: "e",
    ꝫ: "et",
    ḟ: "f",
    ƒ: "f",
    ᵮ: "f",
    ᶂ: "f",
    ǵ: "g",
    ğ: "g",
    ǧ: "g",
    ģ: "g",
    ĝ: "g",
    ġ: "g",
    ɠ: "g",
    ḡ: "g",
    ᶃ: "g",
    ǥ: "g",
    ḫ: "h",
    ȟ: "h",
    ḩ: "h",
    ĥ: "h",
    ⱨ: "h",
    ḧ: "h",
    ḣ: "h",
    ḥ: "h",
    ɦ: "h",
    ẖ: "h",
    ħ: "h",
    ƕ: "hv",
    í: "i",
    ĭ: "i",
    ǐ: "i",
    î: "i",
    ï: "i",
    ḯ: "i",
    ị: "i",
    ȉ: "i",
    ì: "i",
    ỉ: "i",
    ȋ: "i",
    ī: "i",
    į: "i",
    ᶖ: "i",
    ɨ: "i",
    ĩ: "i",
    ḭ: "i",
    ꝺ: "d",
    ꝼ: "f",
    ᵹ: "g",
    ꞃ: "r",
    ꞅ: "s",
    ꞇ: "t",
    ꝭ: "is",
    ǰ: "j",
    ĵ: "j",
    ʝ: "j",
    ɉ: "j",
    ḱ: "k",
    ǩ: "k",
    ķ: "k",
    ⱪ: "k",
    ꝃ: "k",
    ḳ: "k",
    ƙ: "k",
    ḵ: "k",
    ᶄ: "k",
    ꝁ: "k",
    ꝅ: "k",
    ĺ: "l",
    ƚ: "l",
    ɬ: "l",
    ľ: "l",
    ļ: "l",
    ḽ: "l",
    ȴ: "l",
    ḷ: "l",
    ḹ: "l",
    ⱡ: "l",
    ꝉ: "l",
    ḻ: "l",
    ŀ: "l",
    ɫ: "l",
    ᶅ: "l",
    ɭ: "l",
    ł: "l",
    ǉ: "lj",
    ſ: "s",
    ẜ: "s",
    ẛ: "s",
    ẝ: "s",
    ḿ: "m",
    ṁ: "m",
    ṃ: "m",
    ɱ: "m",
    ᵯ: "m",
    ᶆ: "m",
    ń: "n",
    ň: "n",
    ņ: "n",
    ṋ: "n",
    ȵ: "n",
    ṅ: "n",
    ṇ: "n",
    ǹ: "n",
    ɲ: "n",
    ṉ: "n",
    ƞ: "n",
    ᵰ: "n",
    ᶇ: "n",
    ɳ: "n",
    ñ: "n",
    ǌ: "nj",
    ó: "o",
    ŏ: "o",
    ǒ: "o",
    ô: "o",
    ố: "o",
    ộ: "o",
    ồ: "o",
    ổ: "o",
    ỗ: "o",
    ö: "o",
    ȫ: "o",
    ȯ: "o",
    ȱ: "o",
    ọ: "o",
    ő: "o",
    ȍ: "o",
    ò: "o",
    ỏ: "o",
    ơ: "o",
    ớ: "o",
    ợ: "o",
    ờ: "o",
    ở: "o",
    ỡ: "o",
    ȏ: "o",
    ꝋ: "o",
    ꝍ: "o",
    ⱺ: "o",
    ō: "o",
    ṓ: "o",
    ṑ: "o",
    ǫ: "o",
    ǭ: "o",
    ø: "o",
    ǿ: "o",
    õ: "o",
    ṍ: "o",
    ṏ: "o",
    ȭ: "o",
    ƣ: "oi",
    ꝏ: "oo",
    ɛ: "e",
    ᶓ: "e",
    ɔ: "o",
    ᶗ: "o",
    ȣ: "ou",
    ṕ: "p",
    ṗ: "p",
    ꝓ: "p",
    ƥ: "p",
    ᵱ: "p",
    ᶈ: "p",
    ꝕ: "p",
    ᵽ: "p",
    ꝑ: "p",
    ꝙ: "q",
    ʠ: "q",
    ɋ: "q",
    ꝗ: "q",
    ŕ: "r",
    ř: "r",
    ŗ: "r",
    ṙ: "r",
    ṛ: "r",
    ṝ: "r",
    ȑ: "r",
    ɾ: "r",
    ᵳ: "r",
    ȓ: "r",
    ṟ: "r",
    ɼ: "r",
    ᵲ: "r",
    ᶉ: "r",
    ɍ: "r",
    ɽ: "r",
    ↄ: "c",
    ꜿ: "c",
    ɘ: "e",
    ɿ: "r",
    ś: "s",
    ṥ: "s",
    š: "s",
    ṧ: "s",
    ş: "s",
    ŝ: "s",
    ș: "s",
    ṡ: "s",
    ṣ: "s",
    ṩ: "s",
    ʂ: "s",
    ᵴ: "s",
    ᶊ: "s",
    ȿ: "s",
    ɡ: "g",
    ᴑ: "o",
    ᴓ: "o",
    ᴝ: "u",
    ť: "t",
    ţ: "t",
    ṱ: "t",
    ț: "t",
    ȶ: "t",
    ẗ: "t",
    ⱦ: "t",
    ṫ: "t",
    ṭ: "t",
    ƭ: "t",
    ṯ: "t",
    ᵵ: "t",
    ƫ: "t",
    ʈ: "t",
    ŧ: "t",
    ᵺ: "th",
    ɐ: "a",
    ᴂ: "ae",
    ǝ: "e",
    ᵷ: "g",
    ɥ: "h",
    ʮ: "h",
    ʯ: "h",
    ᴉ: "i",
    ʞ: "k",
    ꞁ: "l",
    ɯ: "m",
    ɰ: "m",
    ᴔ: "oe",
    ɹ: "r",
    ɻ: "r",
    ɺ: "r",
    ⱹ: "r",
    ʇ: "t",
    ʌ: "v",
    ʍ: "w",
    ʎ: "y",
    ꜩ: "tz",
    ú: "u",
    ŭ: "u",
    ǔ: "u",
    û: "u",
    ṷ: "u",
    ü: "u",
    ǘ: "u",
    ǚ: "u",
    ǜ: "u",
    ǖ: "u",
    ṳ: "u",
    ụ: "u",
    ű: "u",
    ȕ: "u",
    ù: "u",
    ủ: "u",
    ư: "u",
    ứ: "u",
    ự: "u",
    ừ: "u",
    ử: "u",
    ữ: "u",
    ȗ: "u",
    ū: "u",
    ṻ: "u",
    ų: "u",
    ᶙ: "u",
    ů: "u",
    ũ: "u",
    ṹ: "u",
    ṵ: "u",
    ᵫ: "ue",
    ꝸ: "um",
    ⱴ: "v",
    ꝟ: "v",
    ṿ: "v",
    ʋ: "v",
    ᶌ: "v",
    ⱱ: "v",
    ṽ: "v",
    ꝡ: "vy",
    ẃ: "w",
    ŵ: "w",
    ẅ: "w",
    ẇ: "w",
    ẉ: "w",
    ẁ: "w",
    ⱳ: "w",
    ẘ: "w",
    ẍ: "x",
    ẋ: "x",
    ᶍ: "x",
    ý: "y",
    ŷ: "y",
    ÿ: "y",
    ẏ: "y",
    ỵ: "y",
    ỳ: "y",
    ƴ: "y",
    ỷ: "y",
    ỿ: "y",
    ȳ: "y",
    ẙ: "y",
    ɏ: "y",
    ỹ: "y",
    ź: "z",
    ž: "z",
    ẑ: "z",
    ʑ: "z",
    ⱬ: "z",
    ż: "z",
    ẓ: "z",
    ȥ: "z",
    ẕ: "z",
    ᵶ: "z",
    ᶎ: "z",
    ʐ: "z",
    ƶ: "z",
    ɀ: "z",
    ﬀ: "ff",
    ﬃ: "ffi",
    ﬄ: "ffl",
    ﬁ: "fi",
    ﬂ: "fl",
    ĳ: "ij",
    œ: "oe",
    ﬆ: "st",
    ₐ: "a",
    ₑ: "e",
    ᵢ: "i",
    ⱼ: "j",
    ₒ: "o",
    ᵣ: "r",
    ᵤ: "u",
    ᵥ: "v",
    ₓ: "x",
};

export const top300Player = [
    {
        name: "Kylian Mbappé",
        rate: "91",
        country: "France",
        team: "Paris SG",
    },
    {
        name: "Erling Haaland",
        rate: "91",
        country: "Norvège",
        team: "Manchester City",
    },
    {
        name: "Kevin De Bruyne",
        rate: "91",
        country: "Belgique",
        team: "Manchester City",
    },
    {
        name: "Harry Kane",
        rate: "90",
        country: "Angleterre",
        team: "Bayern Munich",
    },
    {
        name: "Robert Lewandowski",
        rate: "90",
        country: "Pologne",
        team: "FC Barcelone",
    },
    {
        name: "Lionel Messi",
        rate: "90",
        country: "Argentine",
        team: "Inter Miami CF",
    },
    {
        name: "Karim Benzema",
        rate: "90",
        country: "France",
        team: "Al Ittihad",
    },
    {
        name: "Thibaut Courtois",
        rate: "90",
        country: "Belgique",
        team: "Real Madrid",
    },
    {
        name: "Neymar Jr",
        rate: "89",
        country: "Brésil",
        team: "Al Hilal",
    },
    {
        name: "Alisson",
        rate: "89",
        country: "Brésil",
        team: "Liverpool",
    },
    {
        name: "Vini Jr.",
        rate: "89",
        country: "Brésil",
        team: "Real Madrid",
    },
    {
        name: "Virgil van Dijk",
        rate: "89",
        country: "Pays-Bas",
        team: "Liverpool",
    },
    {
        name: "Casemiro",
        rate: "89",
        country: "Brésil",
        team: "Manchester United",
    },
    {
        name: "Rúben Dias",
        rate: "89",
        country: "Portugal",
        team: "Manchester City",
    },
    {
        name: "Marc-André ter Stegen",
        rate: "89",
        country: "Allemagne",
        team: "FC Barcelone",
    },
    {
        name: "Mohamed Salah",
        rate: "89",
        country: "Égypte",
        team: "Liverpool",
    },
    {
        name: "Rodri",
        rate: "89",
        country: "Espagne",
        team: "Manchester City",
    },
    {
        name: "Victor Osimhen",
        rate: "88",
        country: "Nigeria",
        team: "Napoli FC",
    },
    {
        name: "Bruno Fernandes",
        rate: "88",
        country: "Portugal",
        team: "Manchester United",
    },
    {
        name: "Bernardo Silva",
        rate: "88",
        country: "Portugal",
        team: "Manchester City",
    },
    {
        name: "Joshua Kimmich",
        rate: "88",
        country: "Allemagne",
        team: "Bayern Munich",
    },
    {
        name: "Ederson",
        rate: "88",
        country: "Brésil",
        team: "Manchester City",
    },
    {
        name: "Antoine Griezmann",
        rate: "88",
        country: "France",
        team: "Atlético Madrid",
    },
    {
        name: "Federico Valverde",
        rate: "88",
        country: "Uruguay",
        team: "Real Madrid",
    },
    {
        name: "Jan Oblak",
        rate: "88",
        country: "Slovénie",
        team: "Atlético Madrid",
    },
    {
        name: "Lautaro Martínez",
        rate: "87",
        country: "Argentine",
        team: "Inter",
    },
    {
        name: "Mike Maignan",
        rate: "87",
        country: "France",
        team: "Milan",
    },
    {
        name: "Gregor Kobel",
        rate: "87",
        country: "Suisse",
        team: "Borussia Dortmund",
    },
    {
        name: "Heung Min Son",
        rate: "87",
        country: "Corée du Sud",
        team: "Tottenham",
    },
    {
        name: "Gianluigi Donnarumma",
        rate: "87",
        country: "Italie",
        team: "Paris SG",
    },
    {
        name: "Marquinhos",
        rate: "87",
        country: "Brésil",
        team: "Paris SG",
    },
    {
        name: "Manuel Neuer",
        rate: "87",
        country: "Allemagne",
        team: "Bayern Munich",
    },
    {
        name: "Luka Modrić",
        rate: "87",
        country: "Croatie",
        team: "Real Madrid",
    },
    {
        name: "Frenkie de Jong",
        rate: "87",
        country: "Pays-Bas",
        team: "FC Barcelone",
    },
    {
        name: "Martin Ødegaard",
        rate: "87",
        country: "Norvège",
        team: "Arsenal",
    },
    {
        name: "Ousmane Dembélé",
        rate: "86",
        country: "France",
        team: "Paris SG",
    },
    {
        name: "Parejo",
        rate: "86",
        country: "Espagne",
        team: "Villarreal CF",
    },
    {
        name: "Sadio Mané",
        rate: "86",
        country: "Sénégal",
        team: "Al Nassr",
    },
    {
        name: "Éder Militão",
        rate: "86",
        country: "Brésil",
        team: "Real Madrid",
    },
    {
        name: "Cristiano Ronaldo",
        rate: "86",
        country: "Portugal",
        team: "Al Nassr",
    },
    {
        name: "Wojciech Szczęsny",
        rate: "86",
        country: "Pologne",
        team: "Juventus",
    },
    {
        name: "Pedri",
        rate: "86",
        country: "Espagne",
        team: "FC Barcelone",
    },
    {
        name: "Matthijs de Ligt",
        rate: "86",
        country: "Pays-Bas",
        team: "Bayern Munich",
    },
    {
        name: "Sergej Milinković-Savić",
        rate: "86",
        country: "Serbie",
        team: "Al Hilal",
    },
    {
        name: "Christopher Nkunku",
        rate: "86",
        country: "France",
        team: "Chelsea",
    },
    {
        name: "João Cancelo",
        rate: "86",
        country: "Portugal",
        team: "FC Barcelone",
    },
    {
        name: "Trent Alexander-Arnold",
        rate: "86",
        country: "Angleterre",
        team: "Liverpool",
    },
    {
        name: "Jude Bellingham",
        rate: "86",
        country: "Angleterre",
        team: "Real Madrid",
    },
    {
        name: "Rafael Leão",
        rate: "86",
        country: "Portugal",
        team: "Milan",
    },
    {
        name: "Nicolò Barella",
        rate: "86",
        country: "Italie",
        team: "Inter",
    },
    {
        name: "Khvicha Kvaratskhelia",
        rate: "86",
        country: "Géorgie",
        team: "Napoli FC",
    },
    {
        name: "Andrew Robertson",
        rate: "86",
        country: "Écosse",
        team: "Liverpool",
    },
    {
        name: "Toni Kroos",
        rate: "86",
        country: "Allemagne",
        team: "Real Madrid",
    },
    {
        name: "Bukayo Saka",
        rate: "86",
        country: "Angleterre",
        team: "Arsenal",
    },
    {
        name: "Sandro Tonali",
        rate: "86",
        country: "Italie",
        team: "Newcastle United",
    },
    {
        name: "Paulo Dybala",
        rate: "86",
        country: "Argentine",
        team: "Roma FC",
    },
    {
        name: "N'Golo Kanté",
        rate: "86",
        country: "France",
        team: "Al Ittihad",
    },
    {
        name: "Riyad Mahrez",
        rate: "86",
        country: "Algérie",
        team: "Al Ahli",
    },
    {
        name: "Jamal Musiala",
        rate: "86",
        country: "Allemagne",
        team: "Bayern Munich",
    },
    {
        name: "Ronald Araujo",
        rate: "86",
        country: "Uruguay",
        team: "FC Barcelone",
    },
    {
        name: "İlkay Gündoğan",
        rate: "86",
        country: "Allemagne",
        team: "FC Barcelone",
    },
    {
        name: "Alessandro Bastoni",
        rate: "85",
        country: "Italie",
        team: "Inter",
    },
    {
        name: "Theo Hernández",
        rate: "85",
        country: "France",
        team: "Milan",
    },
    {
        name: "Ciro Immobile",
        rate: "85",
        country: "Italie",
        team: "Latium",
    },
    {
        name: "Keylor Navas",
        rate: "85",
        country: "Costa Rica",
        team: "Paris SG",
    },
    {
        name: "Antonio Rüdiger",
        rate: "85",
        country: "Allemagne",
        team: "Real Madrid",
    },
    {
        name: "Jack Grealish",
        rate: "85",
        country: "Angleterre",
        team: "Manchester City",
    },
    {
        name: "David Alaba",
        rate: "85",
        country: "Autriche",
        team: "Real Madrid",
    },
    {
        name: "Domenico Berardi",
        rate: "85",
        country: "Italie",
        team: "Sassuolo",
    },
    {
        name: "Yassine Bounou",
        rate: "85",
        country: "Maroc",
        team: "Al Hilal",
    },
    {
        name: "Rodrygo",
        rate: "85",
        country: "Brésil",
        team: "Real Madrid",
    },
    {
        name: "John Stones",
        rate: "85",
        country: "Angleterre",
        team: "Manchester City",
    },
    {
        name: "Diogo Jota",
        rate: "85",
        country: "Portugal",
        team: "Liverpool",
    },
    {
        name: "Aymeric Laporte",
        rate: "85",
        country: "Espagne",
        team: "Al Nassr",
    },
    {
        name: "Emiliano Martínez",
        rate: "85",
        country: "Argentine",
        team: "Aston Villa",
    },
    {
        name: "André Onana",
        rate: "85",
        country: "Cameroun",
        team: "Manchester United",
    },
    {
        name: "Kevin Trapp",
        rate: "85",
        country: "Allemagne",
        team: "Francfort",
    },
    {
        name: "Kieran Trippier",
        rate: "85",
        country: "Angleterre",
        team: "Newcastle United",
    },
    {
        name: "Marcos Acuña",
        rate: "85",
        country: "Argentine",
        team: "Séville FC",
    },
    {
        name: "Giovanni Di Lorenzo",
        rate: "85",
        country: "Italie",
        team: "Napoli FC",
    },
    {
        name: "Thomas Partey",
        rate: "85",
        country: "Ghana",
        team: "Arsenal",
    },
    {
        name: "Marcus Rashford",
        rate: "85",
        country: "Angleterre",
        team: "Manchester United",
    },
    {
        name: "Raphaël Varane",
        rate: "85",
        country: "France",
        team: "Manchester United",
    },
    {
        name: "Florian Wirtz",
        rate: "85",
        country: "Allemagne",
        team: "Leverkusen",
    },
    {
        name: "Hakan Çalhanoğlu",
        rate: "85",
        country: "Turquie",
        team: "Inter",
    },
    {
        name: "Kingsley Coman",
        rate: "85",
        country: "France",
        team: "Bayern Munich",
    },
    {
        name: "Phil Foden",
        rate: "85",
        country: "Angleterre",
        team: "Manchester City",
    },
    {
        name: "Leon Goretzka",
        rate: "85",
        country: "Allemagne",
        team: "Bayern Munich",
    },
    {
        name: "Iago Aspas",
        rate: "85",
        country: "Espagne",
        team: "RC Celta",
    },
    {
        name: "Jules Koundé",
        rate: "85",
        country: "France",
        team: "FC Barcelone",
    },
    {
        name: "Declan Rice",
        rate: "85",
        country: "Angleterre",
        team: "Arsenal",
    },
    {
        name: "Álex Remiro",
        rate: "84",
        country: "Espagne",
        team: "Real Sociedad",
    },
    {
        name: "Bremer",
        rate: "84",
        country: "Brésil",
        team: "Juventus",
    },
    {
        name: "Gabriel Jesus",
        rate: "84",
        country: "Brésil",
        team: "Arsenal",
    },
    {
        name: "Achraf Hakimi",
        rate: "84",
        country: "Maroc",
        team: "Paris SG",
    },
    {
        name: "Mikel Merino",
        rate: "84",
        country: "Espagne",
        team: "Real Sociedad",
    },
    {
        name: "Rúben Neves",
        rate: "84",
        country: "Portugal",
        team: "Al Hilal",
    },
    {
        name: "Leroy Sané",
        rate: "84",
        country: "Allemagne",
        team: "Bayern Munich",
    },
    {
        name: "Bruno Guimarães",
        rate: "84",
        country: "Brésil",
        team: "Newcastle United",
    },
    {
        name: "Rodrigo Javier De Paul",
        rate: "84",
        country: "Argentine",
        team: "Atlético Madrid",
    },
    {
        name: "Gabriel",
        rate: "84",
        country: "Brésil",
        team: "Arsenal",
    },
    {
        name: "Kim Min Jae",
        rate: "84",
        country: "Corée du Sud",
        team: "Bayern Munich",
    },
    {
        name: "Koke",
        rate: "84",
        country: "Espagne",
        team: "Atlético Madrid",
    },
    {
        name: "Stanislav Lobotka",
        rate: "84",
        country: "Slovaquie",
        team: "Napoli FC",
    },
    {
        name: "Yann Sommer",
        rate: "84",
        country: "Suisse",
        team: "Inter",
    },
    {
        name: "Niklas Süle",
        rate: "84",
        country: "Allemagne",
        team: "Borussia Dortmund",
    },
    {
        name: "Ismaël Bennacer",
        rate: "84",
        country: "Algérie",
        team: "Milan",
    },
    {
        name: "Federico Chiesa",
        rate: "84",
        country: "Italie",
        team: "Juventus",
    },
    {
        name: "Memphis Depay",
        rate: "84",
        country: "Pays-Bas",
        team: "Atlético Madrid",
    },
    {
        name: "Gabriel Martinelli",
        rate: "84",
        country: "Brésil",
        team: "Arsenal",
    },
    {
        name: "Lucas Hernández",
        rate: "84",
        country: "France",
        team: "Paris SG",
    },
    {
        name: "Pierre-Emile Højbjerg",
        rate: "84",
        country: "Danemark",
        team: "Tottenham",
    },
    {
        name: "Kalidou Koulibaly",
        rate: "84",
        country: "Sénégal",
        team: "Al Hilal",
    },
    {
        name: "Luis Alberto",
        rate: "84",
        country: "Espagne",
        team: "Latium",
    },
    {
        name: "Chris Smalling",
        rate: "84",
        country: "Angleterre",
        team: "Roma FC",
    },
    {
        name: "Fikayo Tomori",
        rate: "84",
        country: "Angleterre",
        team: "Milan",
    },
    {
        name: "Yannick Carrasco",
        rate: "84",
        country: "Belgique",
        team: "Al Shabab",
    },
    {
        name: "Moussa Diaby",
        rate: "84",
        country: "France",
        team: "Aston Villa",
    },
    {
        name: "Luis Díaz",
        rate: "84",
        country: "Colombie",
        team: "Liverpool",
    },
    {
        name: "Serge Gnabry",
        rate: "84",
        country: "Allemagne",
        team: "Bayern Munich",
    },
    {
        name: "Péter Gulácsi",
        rate: "84",
        country: "Hongrie",
        team: "RB Leipzig",
    },
    {
        name: "Reece James",
        rate: "84",
        country: "Angleterre",
        team: "Chelsea",
    },
    {
        name: "Romelu Lukaku",
        rate: "84",
        country: "Belgique",
        team: "Roma FC",
    },
    {
        name: "Marcos Llorente",
        rate: "84",
        country: "Espagne",
        team: "Atlético Madrid",
    },
    {
        name: "Thomas Müller",
        rate: "84",
        country: "Allemagne",
        team: "Bayern Munich",
    },
    {
        name: "Aaron Ramsdale",
        rate: "84",
        country: "Angleterre",
        team: "Arsenal",
    },
    {
        name: "Raphinha",
        rate: "84",
        country: "Brésil",
        team: "FC Barcelone",
    },
    {
        name: "Aurélien Tchouaméni",
        rate: "84",
        country: "France",
        team: "Real Madrid",
    },
    {
        name: "Thiago Silva",
        rate: "84",
        country: "Brésil",
        team: "Chelsea",
    },
    {
        name: "Julian Brandt",
        rate: "84",
        country: "Allemagne",
        team: "Borussia Dortmund",
    },
    {
        name: "Koen Casteels",
        rate: "84",
        country: "Belgique",
        team: "VfL Wolfsbourg",
    },
    {
        name: "Fabinho",
        rate: "84",
        country: "Brésil",
        team: "Al Ittihad",
    },
    {
        name: "Matthias Ginter",
        rate: "84",
        country: "Allemagne",
        team: "SC Fribourg",
    },
    {
        name: "Grimaldo",
        rate: "84",
        country: "Espagne",
        team: "Leverkusen",
    },
    {
        name: "Randal Kolo Muani",
        rate: "84",
        country: "France",
        team: "Paris SG",
    },
    {
        name: "James Maddison",
        rate: "84",
        country: "Angleterre",
        team: "Tottenham",
    },
    {
        name: "Lisandro Martínez",
        rate: "84",
        country: "Argentine",
        team: "Manchester United",
    },
    {
        name: "Nick Pope",
        rate: "84",
        country: "Angleterre",
        team: "Newcastle United",
    },
    {
        name: "Adrien Rabiot",
        rate: "84",
        country: "France",
        team: "Juventus",
    },
    {
        name: "Milan Škriniar",
        rate: "84",
        country: "Slovaquie",
        team: "Paris SG",
    },
    {
        name: "Thiago",
        rate: "84",
        country: "Espagne",
        team: "Liverpool",
    },
    {
        name: "Kyle Walker",
        rate: "84",
        country: "Angleterre",
        team: "Manchester City",
    },
    {
        name: "Francesco Acerbi",
        rate: "83",
        country: "Italie",
        team: "Inter",
    },
    {
        name: "Borja Iglesias",
        rate: "83",
        country: "Espagne",
        team: "Real Betis",
    },
    {
        name: "Sven Botman",
        rate: "83",
        country: "Pays-Bas",
        team: "Newcastle United",
    },
    {
        name: "Filip Kostić",
        rate: "83",
        country: "Serbie",
        team: "Juventus",
    },
    {
        name: "Palhinha",
        rate: "83",
        country: "Portugal",
        team: "Fulham",
    },
    {
        name: "Alessio Romagnoli",
        rate: "83",
        country: "Italie",
        team: "Latium",
    },
    {
        name: "Nico Schlotterbeck",
        rate: "83",
        country: "Allemagne",
        team: "Borussia Dortmund",
    },
    {
        name: "Sergio Busquets",
        rate: "83",
        country: "Espagne",
        team: "Inter Miami CF",
    },
    {
        name: "Emre Can",
        rate: "83",
        country: "Allemagne",
        team: "Borussia Dortmund",
    },
    {
        name: "Andreas Christensen",
        rate: "83",
        country: "Danemark",
        team: "FC Barcelone",
    },
    {
        name: "Jeremie Frimpong",
        rate: "83",
        country: "Pays-Bas",
        team: "Leverkusen",
    },
    {
        name: "Jonas Hofmann",
        rate: "83",
        country: "Allemagne",
        team: "Leverkusen",
    },
    {
        name: "Mats Hummels",
        rate: "83",
        country: "Allemagne",
        team: "Borussia Dortmund",
    },
    {
        name: "Alexandre Lacazette",
        rate: "83",
        country: "France",
        team: "Olympique Lyonnais",
    },
    {
        name: "Morata",
        rate: "83",
        country: "Espagne",
        team: "Atlético Madrid",
    },
    {
        name: "Pau Torres",
        rate: "83",
        country: "Espagne",
        team: "Aston Villa",
    },
    {
        name: "Guido Rodríguez",
        rate: "83",
        country: "Argentine",
        team: "Real Betis",
    },
    {
        name: "Sergi Darder",
        rate: "83",
        country: "Espagne",
        team: "RCD Majorque",
    },
    {
        name: "Dušan Vlahović",
        rate: "83",
        country: "Serbie",
        team: "Juventus",
    },
    {
        name: "Marcelo Brozović",
        rate: "83",
        country: "Croatie",
        team: "Al Nassr",
    },
    {
        name: "Dani Olmo",
        rate: "83",
        country: "Espagne",
        team: "RB Leipzig",
    },
    {
        name: "Enzo Fernández",
        rate: "83",
        country: "Argentine",
        team: "Chelsea",
    },
    {
        name: "Cody Gakpo",
        rate: "83",
        country: "Pays-Bas",
        team: "Liverpool",
    },
    {
        name: "Gavi",
        rate: "83",
        country: "Espagne",
        team: "FC Barcelone",
    },
    {
        name: "José María Giménez",
        rate: "83",
        country: "Uruguay",
        team: "Atlético Madrid",
    },
    {
        name: "Konrad Laimer",
        rate: "83",
        country: "Autriche",
        team: "Bayern Munich",
    },
    {
        name: "Marco Asensio",
        rate: "83",
        country: "Espagne",
        team: "Paris SG",
    },
    {
        name: "Alex Meret",
        rate: "83",
        country: "Italie",
        team: "Napoli FC",
    },
    {
        name: "Benjamin Pavard",
        rate: "83",
        country: "France",
        team: "Inter",
    },
    {
        name: "Rafa",
        rate: "83",
        country: "Portugal",
        team: "SL Benfica",
    },
    {
        name: "William Saliba",
        rate: "83",
        country: "France",
        team: "Arsenal",
    },
    {
        name: "Patrik Schick",
        rate: "83",
        country: "République tchèque",
        team: "Leverkusen",
    },
    {
        name: "Luke Shaw",
        rate: "83",
        country: "Angleterre",
        team: "Manchester United",
    },
    {
        name: "Wissam Ben Yedder",
        rate: "83",
        country: "France",
        team: "AS Monaco",
    },
    {
        name: "Alphonso Davies",
        rate: "83",
        country: "Canada",
        team: "Bayern Munich",
    },
    {
        name: "Ángel Di María",
        rate: "83",
        country: "Argentine",
        team: "SL Benfica",
    },
    {
        name: "Christian Eriksen",
        rate: "83",
        country: "Danemark",
        team: "Manchester United",
    },
    {
        name: "Gerard Moreno",
        rate: "83",
        country: "Espagne",
        team: "Villarreal CF",
    },
    {
        name: "Sébastien Haller",
        rate: "83",
        country: "Côte d'Ivoire",
        team: "Borussia Dortmund",
    },
    {
        name: "Jorginho",
        rate: "83",
        country: "Italie",
        team: "Arsenal",
    },
    {
        name: "Gianluca Mancini",
        rate: "83",
        country: "Italie",
        team: "Roma FC",
    },
    {
        name: "Willi Orban",
        rate: "83",
        country: "Hongrie",
        team: "RB Leipzig",
    },
    {
        name: "Oyarzabal",
        rate: "83",
        country: "Espagne",
        team: "Real Sociedad",
    },
    {
        name: "Lorenzo Pellegrini",
        rate: "83",
        country: "Italie",
        team: "Roma FC",
    },
    {
        name: "Marco Reus",
        rate: "83",
        country: "Allemagne",
        team: "Borussia Dortmund",
    },
    {
        name: "Raheem Sterling",
        rate: "83",
        country: "Angleterre",
        team: "Chelsea",
    },
    {
        name: "André-Franck Zambo Anguissa",
        rate: "83",
        country: "Cameroun",
        team: "Napoli FC",
    },
    {
        name: "Edin Džeko",
        rate: "83",
        country: "Bosnie-Herzégovine",
        team: "Fenerbahçe",
    },
    {
        name: "Nabil Fekir",
        rate: "83",
        country: "France",
        team: "Real Betis",
    },
    {
        name: "Jordi Alba",
        rate: "83",
        country: "Espagne",
        team: "Inter Miami CF",
    },
    {
        name: "Hugo Lloris",
        rate: "83",
        country: "France",
        team: "Tottenham",
    },
    {
        name: "Nacho Fernández",
        rate: "83",
        country: "Espagne",
        team: "Real Madrid",
    },
    {
        name: "Unai Simón",
        rate: "83",
        country: "Espagne",
        team: "Athletic Club",
    },
    {
        name: "Piotr Zieliński",
        rate: "83",
        country: "Pologne",
        team: "Napoli FC",
    },
    {
        name: "Manuel Akanji",
        rate: "82",
        country: "Suisse",
        team: "Manchester City",
    },
    {
        name: "Carvajal",
        rate: "82",
        country: "Espagne",
        team: "Real Madrid",
    },
    {
        name: "Ángel Correa",
        rate: "82",
        country: "Argentine",
        team: "Atlético Madrid",
    },
    {
        name: "Boulaye Dia",
        rate: "82",
        country: "Sénégal",
        team: "Salernitana",
    },
    {
        name: "Seko Fofana",
        rate: "82",
        country: "Côte d'Ivoire",
        team: "Al Nassr",
    },
    {
        name: "Isi Palazón",
        rate: "82",
        country: "Espagne",
        team: "Rayo Vallecano",
    },
    {
        name: "Javi Galán",
        rate: "82",
        country: "Espagne",
        team: "Atlético Madrid",
    },
    {
        name: "João Mário",
        rate: "82",
        country: "Portugal",
        team: "SL Benfica",
    },
    {
        name: "Mateo Kovačić",
        rate: "82",
        country: "Croatie",
        team: "Manchester City",
    },
    {
        name: "Robin Le Normand",
        rate: "82",
        country: "Espagne",
        team: "Real Sociedad",
    },
    {
        name: "Jeremías Conan Ledesma",
        rate: "82",
        country: "Argentine",
        team: "Cádiz CF",
    },
    {
        name: "Dominik Livaković",
        rate: "82",
        country: "Croatie",
        team: "Fenerbahçe",
    },
    {
        name: "Anthony Lopes",
        rate: "82",
        country: "Portugal",
        team: "Olympique Lyonnais",
    },
    {
        name: "Donyell Malen",
        rate: "82",
        country: "Pays-Bas",
        team: "Borussia Dortmund",
    },
    {
        name: "Darwin Núñez",
        rate: "82",
        country: "Uruguay",
        team: "Liverpool",
    },
    {
        name: "Nicolás Otamendi",
        rate: "82",
        country: "Argentine",
        team: "SL Benfica",
    },
    {
        name: "Otávio",
        rate: "82",
        country: "Portugal",
        team: "Al Nassr",
    },
    {
        name: "Robert Andrich",
        rate: "82",
        country: "Allemagne",
        team: "Leverkusen",
    },
    {
        name: "Federico Dimarco",
        rate: "82",
        country: "Italie",
        team: "Inter",
    },
    {
        name: "Olivier Giroud",
        rate: "82",
        country: "France",
        team: "Milan",
    },
    {
        name: "Vincenzo Grifo",
        rate: "82",
        country: "Italie",
        team: "SC Fribourg",
    },
    {
        name: "Nuno Mendes",
        rate: "82",
        country: "Portugal",
        team: "Paris SG",
    },
    {
        name: "Jordan Pickford",
        rate: "82",
        country: "Angleterre",
        team: "Everton",
    },
    {
        name: "Ivan Provedel",
        rate: "82",
        country: "Italie",
        team: "Latium",
    },
    {
        name: "Mehdi Taremi",
        rate: "82",
        country: "Iran",
        team: "FC Porto",
    },
    {
        name: "Youri Tielemans",
        rate: "82",
        country: "Belgique",
        team: "Aston Villa",
    },
    {
        name: "Dayot Upamecano",
        rate: "82",
        country: "France",
        team: "Bayern Munich",
    },
    {
        name: "Callum Wilson",
        rate: "82",
        country: "Angleterre",
        team: "Newcastle United",
    },
    {
        name: "Granit Xhaka",
        rate: "82",
        country: "Suisse",
        team: "Leverkusen",
    },
    {
        name: "Rodrigo Bentancur",
        rate: "82",
        country: "Uruguay",
        team: "Tottenham",
    },
    {
        name: "David García",
        rate: "82",
        country: "Espagne",
        team: "CA Osasuna",
    },
    {
        name: "Stefan de Vrij",
        rate: "82",
        country: "Pays-Bas",
        team: "Inter",
    },
    {
        name: "Ferran Torres",
        rate: "82",
        country: "Espagne",
        team: "FC Barcelone",
    },
    {
        name: "Mark Flekken",
        rate: "82",
        country: "Pays-Bas",
        team: "Brentford",
    },
    {
        name: "Kai Havertz",
        rate: "82",
        country: "Allemagne",
        team: "Arsenal",
    },
    {
        name: "Joelinton",
        rate: "82",
        country: "Brésil",
        team: "Newcastle United",
    },
    {
        name: "Presnel Kimpembe",
        rate: "82",
        country: "France",
        team: "Paris SG",
    },
    {
        name: "Mario Hermoso",
        rate: "82",
        country: "Espagne",
        team: "Atlético Madrid",
    },
    {
        name: "Édouard Mendy",
        rate: "82",
        country: "Sénégal",
        team: "Al Ahli",
    },
    {
        name: "Nahuel Molina",
        rate: "82",
        country: "Argentine",
        team: "Atlético Madrid",
    },
    {
        name: "Ricardo Horta",
        rate: "82",
        country: "Portugal",
        team: "SC Braga",
    },
    {
        name: "Roberto Firmino",
        rate: "82",
        country: "Brésil",
        team: "Al Ahli",
    },
    {
        name: "Stefan Savić",
        rate: "82",
        country: "Monténégro",
        team: "Atlético Madrid",
    },
    {
        name: "Lucas Torreira",
        rate: "82",
        country: "Uruguay",
        team: "Galatasaray",
    },
    {
        name: "Viktor Tsygankov",
        rate: "82",
        country: "Ukraine",
        team: "Girona FC",
    },
    {
        name: "Timo Werner",
        rate: "82",
        country: "Allemagne",
        team: "RB Leipzig",
    },
    {
        name: "Diogo Costa",
        rate: "82",
        country: "Portugal",
        team: "FC Porto",
    },
    {
        name: "Youssef En-Nesyri",
        rate: "82",
        country: "Maroc",
        team: "Séville FC",
    },
    {
        name: "Gayà",
        rate: "82",
        country: "Espagne",
        team: "Valence CF",
    },
    {
        name: "Mario Götze",
        rate: "82",
        country: "Allemagne",
        team: "Francfort",
    },
    {
        name: "Joško Gvardiol",
        rate: "82",
        country: "Croatie",
        team: "Manchester City",
    },
    {
        name: "Franck Yannick Kessié",
        rate: "82",
        country: "Côte d'Ivoire",
        team: "Al Ahli",
    },
    {
        name: "Orkun Kökçü",
        rate: "82",
        country: "Turquie",
        team: "SL Benfica",
    },
    {
        name: "Manuel Locatelli",
        rate: "82",
        country: "Italie",
        team: "Juventus",
    },
    {
        name: "Alexis Mac Allister",
        rate: "82",
        country: "Argentine",
        team: "Liverpool",
    },
    {
        name: "Loïs Openda",
        rate: "82",
        country: "Belgique",
        team: "RB Leipzig",
    },
    {
        name: "Jadon Sancho",
        rate: "82",
        country: "Angleterre",
        team: "Manchester United",
    },
    {
        name: "Fabian Schär",
        rate: "82",
        country: "Suisse",
        team: "Newcastle United",
    },
    {
        name: "Enes Ünal",
        rate: "82",
        country: "Turquie",
        team: "Getafe CF",
    },
    {
        name: "Guglielmo Vicario",
        rate: "82",
        country: "Italie",
        team: "Tottenham",
    },
    {
        name: "Mattia Zaccagni",
        rate: "82",
        country: "Italie",
        team: "Latium",
    },
    {
        name: "Eduardo Camavinga",
        rate: "82",
        country: "France",
        team: "Real Madrid",
    },
    {
        name: "Fernando",
        rate: "82",
        country: "Brésil",
        team: "Séville FC",
    },
    {
        name: "Raphaël Guerreiro",
        rate: "82",
        country: "Portugal",
        team: "Bayern Munich",
    },
    {
        name: "Iñigo Martínez",
        rate: "82",
        country: "Espagne",
        team: "FC Barcelone",
    },
    {
        name: "Joselu",
        rate: "82",
        country: "Espagne",
        team: "Real Madrid",
    },
    {
        name: "Thomas Lemar",
        rate: "82",
        country: "France",
        team: "Atlético Madrid",
    },
    {
        name: "Noussair Mazraoui",
        rate: "82",
        country: "Maroc",
        team: "Bayern Munich",
    },
    {
        name: "Ferland Mendy",
        rate: "82",
        country: "France",
        team: "Real Madrid",
    },
    {
        name: "Pedro Gonçalves",
        rate: "82",
        country: "Portugal",
        team: "Sporting CP",
    },
    {
        name: "Cristian Romero",
        rate: "82",
        country: "Argentine",
        team: "Tottenham",
    },
    {
        name: "Dominik Szoboszlai",
        rate: "82",
        country: "Hongrie",
        team: "Liverpool",
    },
    {
        name: "Dušan Tadić",
        rate: "82",
        country: "Serbie",
        team: "Fenerbahçe",
    },
    {
        name: "Edson Álvarez",
        rate: "81",
        country: "Mexique",
        team: "West Ham",
    },
    {
        name: "Steven Berghuis",
        rate: "81",
        country: "Pays-Bas",
        team: "Ajax",
    },
    {
        name: "Brais Méndez",
        rate: "81",
        country: "Espagne",
        team: "Real Sociedad",
    },
    {
        name: "Davide Calabria",
        rate: "81",
        country: "Italie",
        team: "Milan",
    },
    {
        name: "Etienne Capoue",
        rate: "81",
        country: "France",
        team: "Villarreal CF",
    },
    {
        name: "Jonathan Clauss",
        rate: "81",
        country: "France",
        team: "Olympique de Marseille",
    },
    {
        name: "Sebastián Coates",
        rate: "81",
        country: "Uruguay",
        team: "Sporting CP",
    },
    {
        name: "Danilo",
        rate: "81",
        country: "Brésil",
        team: "Juventus",
    },
    {
        name: "Arnaut Danjuma",
        rate: "81",
        country: "Pays-Bas",
        team: "Everton",
    },
    {
        name: "Denzel Dumfries",
        rate: "81",
        country: "Pays-Bas",
        team: "Inter",
    },
    {
        name: "Felipe Anderson",
        rate: "81",
        country: "Brésil",
        team: "Latium",
    },
    {
        name: "Fred",
        rate: "81",
        country: "Brésil",
        team: "Fenerbahçe",
    },
    {
        name: "Lukáš Hrádecký",
        rate: "81",
        country: "Finlande",
        team: "Leverkusen",
    },
    {
        name: "Iñaki Williams",
        rate: "81",
        country: "Ghana",
        team: "Athletic Club",
    },
    {
        name: "Daichi Kamada",
        rate: "81",
        country: "Japon",
        team: "Latium",
    },
    {
        name: "Ibrahima Konaté",
        rate: "81",
        country: "France",
        team: "Liverpool",
    },
    {
        name: "Hirving Lozano",
        rate: "81",
        country: "Mexique",
        team: "PSV",
    },
    {
        name: "Lucas Paquetá",
        rate: "81",
        country: "Brésil",
        team: "West Ham",
    },
    {
        name: "Lucas Vázquez",
        rate: "81",
        country: "Espagne",
        team: "Real Madrid",
    },
    {
        name: "Henrikh Mkhitaryan",
        rate: "81",
        country: "Arménie",
        team: "Inter",
    },
    {
        name: "Ivan Rakitić",
        rate: "81",
        country: "Croatie",
        team: "Séville FC",
    },
    {
        name: "Rui Patrício",
        rate: "81",
        country: "Portugal",
        team: "Roma FC",
    },
    {
        name: "Ibrahim Sangaré",
        rate: "81",
        country: "Côte d'Ivoire",
        team: "Nottingham Forest",
    },
    {
        name: "Yeray",
        rate: "81",
        country: "Espagne",
        team: "Athletic Club",
    },
    {
        name: "Duván Zapata",
        rate: "81",
        country: "Colombie",
        team: "Torino",
    },
    {
        name: "Maximilian Arnold",
        rate: "81",
        country: "Allemagne",
        team: "VfL Wolfsbourg",
    },
    {
        name: "Ben Chilwell",
        rate: "81",
        country: "Angleterre",
        team: "Chelsea",
    },
    {
        name: "Bryan Cristante",
        rate: "81",
        country: "Italie",
        team: "Roma FC",
    },
    {
        name: "Diego Carlos",
        rate: "81",
        country: "Brésil",
        team: "Aston Villa",
    },
    {
        name: "Lorenzo Insigne",
        rate: "81",
        country: "Italie",
        team: "Toronto FC",
    },
    {
        name: "Kepa",
        rate: "81",
        country: "Espagne",
        team: "Real Madrid",
    },
];
